# Generated by Django 5.0.6 on 2024-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_admin',
            field=models.BooleanField(default=False),
        ),
    ]
